# Generated by Django 4.1.3 on 2022-11-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rotation_period', models.IntegerField()),
                ('orbital_period', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('climate', models.CharField(max_length=250)),
                ('gravity', models.CharField(max_length=250)),
                ('terrain', models.CharField(max_length=250)),
                ('surface_water', models.IntegerField()),
                ('population', models.IntegerField()),
            ],
        ),
    ]
