# Generated by Django 4.1.3 on 2022-11-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='planets',
            field=models.ManyToManyField(to='planets.planet'),
        ),
    ]
