# Generated by Django 4.1.3 on 2022-11-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='planets',
            field=models.ManyToManyField(blank=True, related_name='movie_planet', to='planets.planet'),
        ),
    ]
